on: push
name: ğŸš€ Deploy Github Pages
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ“š Install dependencies
        run: |
          make install

      - name: ğŸ§ Lint code
        run: |
          make lint

      - name: ğŸš€ Build and Deploy
        run: |
          make deploy
